### ISSUE TITLE
New issue with TBS 8920

### ISSUE THREAD

**Issue by ant-thomas** [ljalves/linux_media#52]
I've been using 2xTBS 8920s and 1xTBS 6982 for a while with no issues.

Updated the driver today and it has caused the 8920s to stop working. They usually work fine with ubuntu with just the firmware being loaded.

syslog paste with the errors - http://paste.ubuntu.com/9284564/

Reverted back to a previous build and they're working again.

**Comment by ljalves** [comment]
I wonder if this issue is also related to the "[media] cx88: convert to vb2" commit that also caused issues on the cx23885 (by "cx23885: convert to vb2") as discovered by @RaiCic

@ant-thomas 
Since this driver is in the official tree, have you tried to compile it and see if this issue also occurs there?

**Comment by ant-thomas** [comment]
I'll see if I can figure that out and give the official media tree a go to test.

The 8920 is definitely supported officially so I doubt it's any changes you have made.

**Comment by ljalves** [comment]
According to Hans (the cx88 driver maintainer) this has been fixed:

"
This is a cx88 bug that's
fixed here:

http://www.spinics.net/lists/linux-media/msg84255.html

Regards,

        Hans
"

**Comment by ant-thomas** [comment]
I have upgraded the kernel on ubuntu 14.04 to 3.18.


Compiled your tree today and everything is now working (after using the make fix here https://github.com/ljalves/linux_media/issues/68).


TBS 8920 and 6982 working in harmony again. Very happy!
